services:
  redis_bp:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "${REDIS_DB_PORT}:6379"
  
  chroma:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc
    volumes:
      - qdrant_data:/data

volumes:
  qdrant_data:
